version: '3.3'

services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy.Dockerfile
    image: 'grpcweb:envoy'
    container_name: 'envoy'
    restart: always
    ports:
      - '8080:8080'
      - '9901:9901'
    depends_on:
      - yorkie
    # If you're using Mac or Windows, this special domain name("host.docker.internal" which makes containers able to connect to the host)
    # is supported by default.
    # But if you're using Linux and want an envoy container to communicate with the host,
    # it may help to define "host.docker.internal" in extra_hosts. 
    # (Actually, other hostnames are available, but in that case you should update clusters[].host configurations of envoy.yaml)
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  yorkie:
    volumes:
    - ./yorkie.json:/app/yorkie.json
    image: 'yorkieteam/yorkie:0.1.6'
    container_name: 'yorkie'
    command: [
      'agent',
      '--mongo-connection-uri',
      'mongodb://mongo:27017',
    ]
    restart: always
    ports:
      - '11101:11101'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    restart: always
    ports:
      - '27017:27017'
